#!/bin/bash

set -e
tabs -2

if [[ "$1" == "-noclear" ]]; then
	shift
else
	clear
fi

printUsage() {
	println "Usage:"
	println "\t" "Terminal is cleared unless '-noclear' flag is provided"
	println "\t" "./godo [-noclear] [help]  " "\t\t" "Print usage"
	println "\t" "./godo [-noclear] clean   " "\t\t" "Clean Go caches"
	println "\t" "./godo [-noclear] tidy    " "\t\t" "Tidy Go mod"
	println "\t" "./godo [-noclear] format  " "\t\t" "Format all Go code"
	println "\t" "./godo [-noclear] build   " "\t\t" "tidy -> format -> build"
	println "\t" "./godo [-noclear] test    " "\t\t" "tidy -> format -> test -> vet"
	println "\t" "./godo [-noclear] run     " "\t\t" "tidy -> format -> run"
	println "\t" "./godo [-noclear] audit   " "\t\t" "clean -> tidy -> format -> build -> test -> vet"
	println "\t" "./godo [-noclear] example1" "\t\t" "Runs example 1: Minimal app"
}

println() {
	for s in "$@"
	do
		printf "$s"
	done
	printf "\\n"
}

godoClean() {
	println "go clean -cache -testcache"
	go clean -cache -testcache
}

godoTidy() {
	println "go mod tidy"
	go mod tidy
}

godoFormat() {
	println "go fmt ./..."
	go fmt ./...
}

godoTest() {
	println "go test ./... -timeout \"2s\""
	go test ./... -timeout "2s"
}

godoBuild() {
	println "go build -o /dev/null ."
	go build -o /dev/null .
}

godoRunExample() {
	println "go run ./examples/$1/..."
	go run "./examples/$1/..."
}

godoVet() {
	println "go vet ./..."
	go vet ./...
}

if [[ "$1" == "" || "$1" == "help" ]]; then
	printUsage
	exit 0
fi

if [[ "$1" == "clean" ]]; then
	godoClean
	exit 0
fi

if [[ "$1" == "tidy" ]]; then
	godoTidy
	exit 0
fi

if [[ "$1" == "format" ]]; then
	godoFormat
	exit 0
fi

if [[ "$1" == "build" ]]; then
	godoTidy
	godoFormat
	godoBuild
	exit 0
fi

if [[ "$1" == "test" ]]; then
	godoTidy
	godoFormat
	godoTest
	godoVet
	exit 0
fi

if [[ "$1" == "run" ]]; then
	godoTidy
	godoFormat
	godoRun
	exit 0
fi

if [[ "$1" == "audit" ]]; then
	godoClean
	godoTidy
	godoFormat
	godoBuild
	godoTest
	godoVet
	exit 0
fi

if [[ "$1" == "example1" ]]; then
	godoRunExample minimal
	exit 0
fi


if [[ "$1" == "purego" ]]; then
	godoRunExample purego
	exit 0
fi

println "I don't understand the option '$1'."
printUsage
exit 1

